### ISSUE TITLE
not enough memory

### ISSUE THREAD

**Issue by spyyps** [yhthu/intercom#1]
help!
fatal exception on google pixel and nubia z11 miniS:
05-23 15:46:24.420 22170-22170/com.jd.wly.intercom E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.jd.wly.intercom, PID: 22170
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jd.wly.intercom/com.jd.wly.intercom.AudioActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.audiofx.AcousticEchoCanceler.setEnabled(boolean)' on a null object reference
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2511)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2571)
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:165)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1409)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:171)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5620)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.audiofx.AcousticEchoCanceler.setEnabled(boolean)' on a null object reference
                                                                         at com.jd.wly.intercom.util.AECUtil.initAEC(AECUtil.java:18)
                                                                         at com.jd.wly.intercom.input.Recorder.<init>(Recorder.java:30)
                                                                         at com.jd.wly.intercom.input.AudioInput.initJobHandler(AudioInput.java:29)
                                                                         at com.jd.wly.intercom.input.AudioInput.<init>(AudioInput.java:22)
                                                                         at com.jd.wly.intercom.AudioActivity.initData(AudioActivity.java:108)
                                                                         at com.jd.wly.intercom.AudioActivity.onCreate(AudioActivity.java:73)
                                                                         at android.app.Activity.performCreate(Activity.java:6320)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1121)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2571) 
                                                                         at android.app.ActivityThread.access$900(ActivityThread.java:165) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1409) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:171) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5620) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)

**Comment by yhthu** [comment]
Sorry, I have removed the AcousticEchoCanceler, And then I used AudioManager.STREAM_VOICE_CALL in AudioTrack initialization, because STREAM_VOICE_CALL can suppress echo itself. This is not a completed project, and  I will optimize it continuously. Thanks!
